import { useQuery } from "@tanstack/react-query";
import { AlertCircle, ArrowDownRight, ArrowUpRight, CalendarDays, ChevronRight, CircleDollarSign, CreditCard, Utensils } from "lucide-react";
import { Area, CartesianGrid, Cell, ComposedChart, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "../../lib/api";
import { formatMoney, formatShortDate } from "../../lib/format";
import type { ApiFixedExpense, ApiGoal, DashboardSummary, TransactionPage } from "../../types";

function monthBounds() { const now=new Date(); const start=new Date(now.getFullYear(),now.getMonth(),1); const end=new Date(now.getFullYear(),now.getMonth()+1,0); const iso=(d:Date)=>d.toISOString().slice(0,10); return {start:iso(start),end:iso(end),label:new Intl.DateTimeFormat("pt-BR",{month:"long",year:"numeric"}).format(now)}; }
function MoneySummary({label,value,tone}:{label:string;value:number;tone:"mint"|"rose"|"ink"}) { const Icon=tone==="rose"?ArrowDownRight:ArrowUpRight; return <div className={`money-summary ${tone}`}><span>{label}</span><strong>{formatMoney(value)}</strong><small><Icon size={14}/>Dados do período</small></div>; }
const colors=["#6fc5ad","#d985a0","#ddb56f","#7d9bc1","#927dae","#8bb4a7"];
export function DashboardPage(){
  const period=monthBounds();
  const summary=useQuery({queryKey:["dashboard",period.start,period.end],queryFn:async()=>(await api.get<DashboardSummary>("/dashboard/summary",{params:{start_date:period.start,end_date:period.end}})).data});
  const transactions=useQuery({queryKey:["transactions","recent"],queryFn:async()=>(await api.get<TransactionPage>("/transactions",{params:{page_size:4}})).data});
  const goals=useQuery({queryKey:["goals"],queryFn:async()=>(await api.get<ApiGoal[]>("/goals")).data});
  const fixed=useQuery({queryKey:["fixed-expenses"],queryFn:async()=>(await api.get<ApiFixedExpense[]>("/fixed-expenses",{params:{is_active:true}})).data});
  const data=summary.data; const categoryData=(data?.expenses_by_category??[]).map((item,index)=>({...item,value:Number(item.total),color:colors[index%colors.length]}));
  const timeline=(data?.timeline??[]).map(item=>({day:new Date(`${item.date}T12:00:00`).getDate(),income:Number(item.total_income),expense:Number(item.total_expense)}));
  const activeGoals=(goals.data??[]).filter(g=>g.is_active).slice(0,3); const due=(fixed.data??[]).slice(0,4); const isLoading=summary.isLoading||transactions.isLoading;
  return <div className="dashboard-page" aria-busy={isLoading}><div className="spectral-line" aria-hidden="true"/><section className="dashboard-heading"><div><h1>Visão geral</h1><p>Seu dinheiro em equilíbrio, mais escolhas para o seu amanhã.</p></div><button className="period-button" disabled><span className="capitalize">{period.label}</span><CalendarDays size={16}/></button></section>
    {summary.isError&&<p className="form-error" role="alert">Não foi possível carregar o resumo financeiro.</p>}
    <div className="dashboard-grid"><div className="dashboard-primary"><section className="summary-strip" aria-label="Resumo financeiro do período"><MoneySummary label="Saldo" value={Number(data?.balance??0)} tone="ink"/><MoneySummary label="Receitas" value={Number(data?.total_income??0)} tone="mint"/><MoneySummary label="Gastos" value={Number(data?.total_expense??0)} tone="rose"/></section>
      <section className="cashflow-section"><div className="section-title-row"><div><h2>Receitas e gastos ao longo do mês</h2><p>Movimento diário</p></div><div className="chart-legend"><span className="mint-dot"/>Receitas<span className="rose-dot"/>Gastos</div></div><div className="cashflow-chart"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={timeline} margin={{top:18,right:8,bottom:0,left:-20}}><defs><linearGradient id="mintArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#9adbc5" stopOpacity={.28}/><stop offset="100%" stopColor="#9adbc5" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fill:"var(--muted)"}}/><YAxis tickLine={false} axisLine={false} tick={{fill:"var(--muted)"}}/><Tooltip contentStyle={{background:"var(--surface-elevated)",borderColor:"var(--rule)",borderRadius:10,color:"var(--ink)"}} formatter={(value:number)=>formatMoney(value)}/><Area type="monotone" dataKey="income" stroke="none" fill="url(#mintArea)"/><Line type="monotone" dataKey="income" stroke="#6fc5ad" strokeWidth={2.2}/><Line type="monotone" dataKey="expense" stroke="#d985a0" strokeWidth={2.2}/></ComposedChart></ResponsiveContainer></div></section>
      <div className="lower-insights"><section className="category-section"><div className="section-title-row"><h2>Distribuição dos gastos</h2></div><div className="category-content"><div className="donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={categoryData} dataKey="value" nameKey="category_name" innerRadius="62%" outerRadius="88%">{categoryData.map(entry=><Cell key={entry.category_id} fill={entry.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="donut-center"><strong>{formatMoney(Number(data?.total_expense??0))}</strong><span>gastos no mês</span></div></div><ul className="category-list">{categoryData.map(item=><li key={item.category_id}><span className="category-color" style={{background:item.color}}/><span>{item.category_name}</span><em>{Math.round(item.percentage)}%</em><strong>{formatMoney(item.value)}</strong></li>)}</ul></div></section><section className="insight-section"><div className="insight-item"><span className="insight-icon"><CircleDollarSign size={21}/></span><p>Seu saldo no período é <strong>{formatMoney(Number(data?.balance??0))}</strong>.</p></div><div className="insight-item"><span className="insight-icon"><AlertCircle size={21}/></span><p>{activeGoals.filter(g=>g.is_exceeded).length} meta(s) ultrapassada(s) neste mês.</p></div></section></div>
      <section className="transactions-section"><div className="section-title-row"><h2>Transações recentes</h2><button>Ver todas <ChevronRight size={15}/></button></div><div className="transaction-table" role="table"><div className="transaction-row transaction-head"><span>Data</span><span>Descrição</span><span>Categoria</span><span>Valor</span></div>{(transactions.data?.items??[]).map(item=><div className="transaction-row" key={item.id}><span>{formatShortDate(item.transaction_date)}</span><span><span className="mini-icon"><Utensils size={14}/></span>{item.description||"Sem descrição"}</span><span>{item.category_name}</span><strong className={item.type}>{item.type==="expense"?"−":"+"} {formatMoney(Number(item.amount))}</strong></div>)}</div>{!transactions.isLoading&&!transactions.data?.items.length&&<p className="empty-row">Nenhuma transação neste período.</p>}</section>
    </div><aside className="dashboard-observations"><section className="attention-block"><AlertCircle size={24}/><div><strong>Dados ao vivo</strong><p>Este painel é recalculado a partir dos lançamentos armazenados no banco.</p></div></section><section className="goals-section"><div className="section-title-row"><h2>Metas</h2></div><div className="goal-list">{activeGoals.map(goal=>{const percentage=Math.round(Number(goal.current_month_spent)/Number(goal.monthly_limit)*100);return <div className="goal-item" key={goal.id}><span className="round-icon"><CircleDollarSign size={19}/></span><div><strong>{goal.category_name}</strong><p>{formatMoney(Number(goal.current_month_spent))} de {formatMoney(Number(goal.monthly_limit))}</p><div className="progress"><span style={{width:`${Math.min(percentage,100)}%`}}/></div></div><em>{percentage}%</em></div>})}{!goals.isLoading&&!activeGoals.length&&<p className="empty-row">Sem metas ativas.</p>}</div></section><section className="due-section"><div className="section-title-row"><h2>Próximos vencimentos</h2></div><div className="due-list">{due.map(expense=><div className="due-item" key={expense.id}><span className="round-icon"><CreditCard size={18}/></span><div><strong>{expense.description}</strong><p>Dia {expense.due_day}</p></div><strong>{formatMoney(Number(expense.amount))}</strong></div>)}{!fixed.isLoading&&!due.length&&<p className="empty-row">Sem gastos fixos ativos.</p>}</div></section></aside></div>
  </div>;
}
