import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BellRing, Check, Globe2, UserRound } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { PageHeader } from "../../components/PageHeader";
import { api } from "../../lib/api";
import type { NotificationPreference, UserProfile } from "../../types";
import { useAuthStore } from "../auth/store";

export function SettingsPage() {
  const client=useQueryClient(); const stored=useAuthStore(s=>s.user); const setUser=useAuthStore(s=>s.setUser); const [saved,setSaved]=useState(false);
  const [name,setName]=useState(stored?.name??""); const [currency,setCurrency]=useState(stored?.default_currency??"BRL"); const [goalAlert,setGoalAlert]=useState(true); const [dueAlert,setDueAlert]=useState(true); const [days,setDays]=useState(3);
  const me=useQuery({queryKey:["current-user"],queryFn:async()=>(await api.get<UserProfile>("/auth/me")).data});
  const prefs=useQuery({queryKey:["notification-preferences"],queryFn:async()=>(await api.get<NotificationPreference>("/notification-preferences")).data});
  useEffect(()=>{if(me.data){setName(me.data.name);setCurrency(me.data.default_currency);}},[me.data]);
  useEffect(()=>{if(prefs.data){setGoalAlert(prefs.data.notify_goal_exceeded);setDueAlert(prefs.data.notify_fixed_expense_due);setDays(prefs.data.fixed_expense_due_days_before);}},[prefs.data]);
  const save=useMutation({mutationFn:async()=>{const [user]=await Promise.all([api.patch<UserProfile>("/auth/me",{name,default_currency:currency}),api.patch("/notification-preferences",{notify_goal_exceeded:goalAlert,notify_fixed_expense_due:dueAlert,fixed_expense_due_days_before:days})]);return user.data;},onSuccess:async(user)=>{setUser(user);setSaved(true);await Promise.all([client.invalidateQueries({queryKey:["current-user"]}),client.invalidateQueries({queryKey:["notification-preferences"]}),client.invalidateQueries({queryKey:["dashboard"]})]);setTimeout(()=>setSaved(false),2500);}});
  return <div className="feature-page"><PageHeader title="Configurações" description="Preferências da sua conta e do jeito como o Vault conversa com você."/>
    <form className="settings-layout" onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate();}}><nav><a href="#profile" className="active"><UserRound/>Perfil</a><a href="#currency"><Globe2/>Moeda</a><a href="#notifications"><BellRing/>Notificações</a></nav><div className="settings-panels"><section id="profile"><header><h2>Perfil</h2><p>Informações usadas na sua experiência.</p></header><div className="settings-fields"><label>Nome<input value={name} minLength={2} required onChange={e=>setName(e.target.value)}/></label><label>E-mail<input type="email" value={me.data?.email??stored?.email??""} disabled/><small>O e-mail identifica a sua conta.</small></label></div></section><section id="currency"><header><h2>Moeda padrão</h2><p>Usada para consolidar o dashboard.</p></header><label>Moeda<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="BRL">Real brasileiro — BRL</option><option value="USD">Dólar americano — USD</option><option value="EUR">Euro — EUR</option></select></label></section><section id="notifications"><header><h2>Notificações por e-mail</h2><p>Escolha quais sinais merecem chegar até você.</p></header><label className="toggle-row"><span><strong>Meta ultrapassada</strong><small>Quando uma categoria passa do limite mensal.</small></span><input type="checkbox" checked={goalAlert} onChange={e=>setGoalAlert(e.target.checked)}/></label><label className="toggle-row"><span><strong>Gasto fixo próximo</strong><small>Um lembrete antes do vencimento.</small></span><input type="checkbox" checked={dueAlert} onChange={e=>setDueAlert(e.target.checked)}/></label><label>Dias de antecedência<input type="number" min="0" max="30" value={days} onChange={e=>setDays(Number(e.target.value))}/></label></section><button className="primary-button compact" disabled={save.isPending}><Check size={16}/>{save.isPending?"Salvando...":saved?"Alterações salvas":"Salvar alterações"}</button>{save.isError&&<p className="form-error">Não foi possível salvar as configurações.</p>}</div></form>
  </div>;
}
